# Generated by Django 3.2.18 on 2023-02-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=25, unique=True)),
                ('description', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['category_id'],
            },
        ),
    ]
