# Generated by Django 3.2.18 on 2023-03-26 13:24

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citizen_detectives', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_slug',
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='default-category', editable=False, populate_from='title'),
            preserve_default=False,
        ),
    ]
