# Generated by Django 3.2.18 on 2023-02-17 13:12

import citizen_detectives.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citizen_detectives', '0002_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='tag_catagory',
            field=models.ForeignKey(default=citizen_detectives.models.Category.get_default_pk, on_delete=django.db.models.deletion.CASCADE, to='citizen_detectives.category'),
        ),
    ]
