# Generated by Django 3.2.18 on 2023-02-17 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citizen_detectives', '0003_tag_tag_catagory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tag_catagory',
            new_name='tag_category',
        ),
    ]
