# Generated by Django 3.2.18 on 2023-02-20 18:10

import citizen_detectives.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('citizen_detectives', '0004_rename_tag_catagory_tag_tag_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=15, unique=True)),
                ('post_title', models.CharField(max_length=25)),
                ('post_content', models.TextField()),
                ('post_date', models.DateField(auto_now=True)),
                ('post_author', models.ForeignKey(default='Anonymous', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
                ('post_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen_detectives.category')),
                ('post_likes', models.ManyToManyField(blank=True, related_name='blog_likes', to=settings.AUTH_USER_MODEL)),
                ('post_tag', models.ForeignKey(default=citizen_detectives.models.Tag.get_default_pk, on_delete=django.db.models.deletion.SET_DEFAULT, to='citizen_detectives.tag')),
            ],
        ),
    ]
