# Generated by Django 3.2.18 on 2023-03-01 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citizen_detectives', '0006_auto_20230301_1248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-post_date']},
        ),
    ]
