# Generated by Django 3.2.18 on 2023-03-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen_detectives', '0007_alter_post_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
