# Generated by Django 3.2.18 on 2023-03-02 16:35

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citizen_detectives', '0008_alter_category_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='default', editable=False, populate_from='title'),
            preserve_default=False,
        ),
    ]
