# Generated by Django 3.2.18 on 2023-03-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen_detectives', '0011_alter_post_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='tag',
            name='tag_category',
        ),
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
